---
title: "Review Questions"
output: html_document
---

Informations

Chris: chris.brown **at** decisionpatterns.com
Google Group: CSX460
Github: https://github.com/csx460


All assignments should be submitted to the github repository using a branch created wit you initials. For Example,

    git clone https://github.com/csx460/week2
    git checkout -b ctb
    (work)
    git add ...
    git commit ...
    git push into your repo and issue a pull request.    


Place answers directly in the files.

Feel free to push your answers when you are complete 


Assignments:

* Please Read Chapters 1-3 of Applied Predictive Modeling 


* Submit via email a project proposal: A description of your project that includes:
** The objective, what you expect to achieve with the model
** data source(s)
** responses
** expected (hypothesized) predictors
** how the model will be used 
** how you will determine the measure of success of the model


# 1.  Do the boston-housing.Rmd assignment in github.
Don't forget to show your works, plots included.

> See boston-housing.html


# 2. Algorithms and Functions

When speaking of Machine Learning, there are two functions or algorithms involved.
Describe and differentiate the algorithms from the function.

> An algorithm are a general set of operations performed to solve some sort of problems. A function is an implementation of an algorithm that solves actual and specific problems.


# 3. RMSE and MAE

Why is RMSE preferrable to MAE? 

> Typically, we are more concerned about points far away from our prediction, because these outliers may seriously affect the validity of our model. Therefore, we put more weight on them by squaring the deviation.

When is MAE better? 

> Sometimes, twice far away from prediction is just twice bad, and there is no need to put more weight on far outliers. In this case, MAE is better and the computer can calculate the error faster than RMSE.
