# Boston Housing

The *mlbench* package contains the data set `BostonHousing`. 

Create a linear regression model that predicts the medium home value of the census tract as a function of the relevant predictors. Please refer to the process diagram from class. Don't forget to examine the response and predictors variable using graphical and other means.  Show your work.

This is a `rmarkdown` Document. You can use `rmarkdown` to produce a Word Doc
file, a presentation, html file, etc. Please just submit the code.

install.packages('AppliedPredictiveModeling')
library(mlbench)
library(magrittr)
library(ggplot2)
data(BostonHousing)



#View the effection that a certain feature of the data with the simple linear model

model1 <- lm( medv ~ .,data = BostonHousing )
summary (model1)

#use the features that have the comparitively high effection
model2 <- lm( medv ~ . -indus - age - tax -crim, data = BostonHousing )

#see the efficiency of the model by viewint the rmse 
rmse(model1$fitted.values, BostonHousing$medv)
rmse(model2$fitted.values, BostonHousing$medv)
#predict (model1,data)
rmse(model1$fitted.values, BostonHousing$medv)


ggplot( aes(x=medv, y=model1$fitted.values), data=BostonHousing ) + geom_point() +
  coord_equal( ylim=c(0,50), xlim=c(0,50) ) + 
  geom_abline( slope=1, intercept=0, color="red") +
  xlab( "BostonHousing") + 
  ylab("Estimated BostonHousing") + 
  theme( plot.background = element_blank() )








