# Data Exploration

    install.packages('AppliedPredictiveModeling')
    library(AppliedPredictiveModeling)
    library(ggplot2)
    library(magrittr)

    data(FuelEconomy)


compare_dists <- function (...) 
{
    ll <- list(...)
    nms_1 <- names(ll)
    nms_2 <- as.character(dots(...))
    if (is.null(nms_1)) 
        nms_1 <- nms_2
    nms_1[is.na(nms_1) | nms_1 == ""] <- nms_2[is.na(nms_1) | 
        nms_1 == ""]
    names(ll) <- nms_1
    DF <- NULL
    for (nm in names(ll)) {
        df <- data.frame(dist = nm, value = ll[[nm]])
        DF <- if (is.null(DF)) 
            df
        else rbind(DF, df)
    }
    ggplot(data = DF, aes(x = value, fill = dist)) + geom_histogram() + 
        facet_grid(dist ~ .)
}


# PLOT EACH PR

# Response


# Predictors

## EngDisp
### UNIVARIATE
qplot( cars2010$EngDispl )



## BIVARIATE WITH RESPONSE
ggplot( aes(x=EngDispl, y=FE), data=cars2010 ) +
  geom_point() +
  geom_smooth( method=lm)



## NumCyl : Discrete Numeric
qplot( cars2010$DriveDesc %>% factor )


ggplot( aes(x=NumCyl, y=FE), data=cars2010 ) +
  geom_point() +
  geom_smooth(method=lm)


# Simple Linear Model

fit.1 <- lm( FE ~ EngDispl + NumCyl, data = cars2010 )


fit.3 <- lm( FE ~ EngDispl + NumCyl + Transmission + DriveDesc, data = cars2010 )

rmse(fit.1$fitted.values, cars2010$FE)
rmse(fit.3$fitted.values, cars2010$FE)

fit.3 <- lm( FE ~ . - VarValveTiming, data = cars2010 )

## Compare Distributions
compare_dists( observed=cars2010$FE, fitted=fit$fitted.values ) +
  theme(legend.position = "none") +
  theme(
    # panel.background = element_blank() # element_rect(fill = "transparent",colour = NA)#, # or element_blank()
    # panel.grid.minor = element_blank(), 
    # panel.grid.major = element_blank(),
    plot.background  = element_rect(fill = "transparent",colour = NA)
  )


## Compare Point Estimates

ggplot( aes(x=FE, y=fit.1$fitted.values), data=cars2010 ) + geom_point() + 
  coord_equal( ylim=c(0,70), xlim=c(0,70) ) + 
  geom_abline( slope=1, intercept=0, color="red") +
  xlab( "Fuel Economy") + 
  ylab("Estimated Fuel Economy") + 
  theme( plot.background = element_blank() )

# Stepwise Example

library(MASS)

f <- stepAIC( fit.3, scope=list(lower=FE~1, upper=FE~.), direction="backward" ) 
